### ISSUE TITLE
Image predictor function

### ISSUE THREAD

**Issue by Shakib-IO** [Sarthakdtu/Road-Cracks-Detection-Neural-Network-#6]
I tried to implement but in inline-block 21 you wrote 
from_data_dir = 'original_data/'  
can you explain to me what file contains this directory. 
Also, share the folder structure?

And can you guess why I get this error to predict the image line 22 of your code: image data of dtype object cannot be converted to float?

**Comment by Shakib-IO** [comment]
Are you there ??

**Comment by Sarthakdtu** [comment]
Hey @Shakib-IO, ```original_data/``` contains the actual images of cracks/non-cracks in the form of sub-directory 'positive/', 'negative/'.
Add your images to the directory in following format:-
```original_data/positive/``` -> contains all the crack images
```original_data/negative/``` -> contains all the non-crack images

I will try to share directory structure soon.
Also, if you would like to contribute, you can share the directory structure you followed because it seems you were able to run the code.

For your other question, it is possible that the function is not able to pull images from correct directory and giving None values or perhaps there is error in vector shape.
This [stack-overflow post](https://stackoverflow.com/questions/32302180/typeerror-image-data-can-not-convert-to-float) might help.

Good Luck
